services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pharmassist-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/app/__pycache__
    networks:
      - pharmassist-network
    restart: unless-stopped

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: pharmassist-frontend
#     env_file:
#       - ./frontend/.env
#     ports:
#       - "5173:5173"
#     depends_on:
#       - backend
#     networks:
#       - pharmassist-network
#     restart: unless-stopped

networks:
  pharmassist-network:
    driver: bridge
